vich_uploader:
  db_driver: orm

  mappings:
    products:
      uri_prefix: /images/ShopItem
      upload_destination: '%kernel.project_dir%/public/images/ShopItem'
      namer: Vich\UploaderBundle\Naming\UniqidNamer